/*
 * DO NOT EDIT!
 *
 * This file was generated by the Breeze XML Studio code generator.
 *
 *        Project: file:/C:/nbA/Requirement/EMSIAPS.xsd Binding
 *     Class Name: Address
 *           Date: Mon Nov 11 14:43:37 CST 2002
 * Breeze Version: 3.0.0 build 382
 *
 * IMPORTANT: Please see your Breeze license for more information on
 *            where and how this generated code may be used.
 *
 */

package com.csc.fsg.nba.provideradapter.emsischema;


import java.io.InputStream;
import java.io.OutputStream;

import com.tbf.xml.FormattedOutputStream;
import com.tbf.xml.Validateable;
import com.tbf.xml.XmlAttributeList;
import com.tbf.xml.XmlElement;
import com.tbf.xml.XmlIntegerValidator;
import com.tbf.xml.XmlNamespaceManager;
import com.tbf.xml.XmlObject;
import com.tbf.xml.XmlOutputStream;
import com.tbf.xml.XmlStringValidator;
import com.tbf.xml.XmlValidationError;
import com.tbf.xml.XmlValidator;

/**
 * Address class.
 *
 */
public class Address
	implements com.tbf.xml.XmlObject,
	com.tbf.xml.Validateable,
	java.io.Serializable {

	/**
	 * Constant for "tc" node name.
	 */
	public static final String $TC = "tc";

	/**
	 * Constant for "Zip" node name.
	 */
	public static final String $ZIP = "Zip";

	/**
	 * Constant for "State" node name.
	 */
	public static final String $STATE = "State";

	/**
	 * Constant for "City" node name.
	 */
	public static final String $CITY = "City";

	/**
	 * Constant for "StreetAddress" node name.
	 */
	public static final String $STREET_ADDRESS = "StreetAddress";

	/**
	 * Constant for "Address" node name.
	 */
	public static final String $ADDRESS = "Address";


	/**
	 * Declarations for the XML related fields.
	 */
	protected String _StreetAddress = null;
	protected String _City = null;
	protected String _State = null;
	protected String _Zip = null;
	protected int _Tc = -1;
	protected boolean _has_Tc_ = false;


	/**
	 * Holds the parent object of this object.
	 */
	protected transient XmlObject _parent_ = null;


	/**
	 * Storage for UNEXPECTED_XML errors.
	 */
	protected transient java.util.Vector _unexpected_xml_errors_ = null;


	/**
	 * Default no args constructor.
	 */
	public Address () {
	}


	/**
	 * Creates and populates an instance from the provided parse tree.
	 *
	 * @param  xml  the parse tree
	 */
	public Address (XmlElement xml) {
		unmarshal(xml);
	}


	/**
	 * Creates and populates an instance from the provided parse tree.
	 *
	 * @param  xml  the parse tree
	 * @param  parent  the containibg XmlObject
	 */
	public Address (XmlElement xml, XmlObject parent) {
		_parent_ = parent;
		unmarshal(xml);
	}


	/**
	 * Get the StreetAddress property.
	 */
	public String getStreetAddress () {
		return (_StreetAddress);
	}


	/**
	 * Set the StreetAddress property.
	 */
	public void setStreetAddress (String newValue) {
		_StreetAddress = newValue;
	}


	/**
	 * Checks for whether StreetAddress is set or not.
	 *
	 * @return true if StreetAddress is set, false if not
	 */
	 public boolean hasStreetAddress () {
		return (_StreetAddress != null);
	}


	/**
	 * Discards StreetAddress's value.
	 */
	 public void deleteStreetAddress () {
		_StreetAddress = null;
	}


	/**
	 * Get the City property.
	 */
	public String getCity () {
		return (_City);
	}


	/**
	 * Set the City property.
	 */
	public void setCity (String newValue) {
		_City = newValue;
	}


	/**
	 * Checks for whether City is set or not.
	 *
	 * @return true if City is set, false if not
	 */
	 public boolean hasCity () {
		return (_City != null);
	}


	/**
	 * Discards City's value.
	 */
	 public void deleteCity () {
		_City = null;
	}


	/**
	 * Get the State property.
	 */
	public String getState () {
		return (_State);
	}


	/**
	 * Set the State property.
	 */
	public void setState (String newValue) {
		_State = newValue;
	}


	/**
	 * Checks for whether State is set or not.
	 *
	 * @return true if State is set, false if not
	 */
	 public boolean hasState () {
		return (_State != null);
	}


	/**
	 * Discards State's value.
	 */
	 public void deleteState () {
		_State = null;
	}


	/**
	 * Get the Zip property.
	 */
	public String getZip () {
		return (_Zip);
	}


	/**
	 * Set the Zip property.
	 */
	public void setZip (String newValue) {
		_Zip = newValue;
	}


	/**
	 * Checks for whether Zip is set or not.
	 *
	 * @return true if Zip is set, false if not
	 */
	 public boolean hasZip () {
		return (_Zip != null);
	}


	/**
	 * Discards Zip's value.
	 */
	 public void deleteZip () {
		_Zip = null;
	}


	/**
	 * Get the Tc property.
	 */
	public int getTc () {
		if (_has_Tc_) {
			return (_Tc);
		}

		return (-1);
	}


	/**
	 * Set the Tc property.
	 */
	public void setTc (int new_value) {
		_Tc = new_value;
		_has_Tc_ = true;
		_format_errors.remove("Address.Tc");
	}


	public void setTc (String new_value) {

		if (new_value == null) {
			_Tc = -1;
			_has_Tc_ = false;
			return;
		}

		try {
			_Tc = Integer.parseInt(new_value);
			_has_Tc_ = true;
			_format_errors.remove("Address.Tc");
		} catch (NumberFormatException nfe) {
			_has_Tc_ = false;
			XmlValidationError.addValidityFormatError(
				_format_errors, "Address.Tc", "Attribute",
				"Address/tc", new_value);
		}
	}


	/**
	 * Checks for whether Tc is set or not.
	 *
	 * @return true if Tc is set, false if not
	 */
	public boolean hasTc () {
		return (_has_Tc_);
	}


	/**
	 * Discards Tc's value.
	 */
	public void deleteTc () {
		_has_Tc_ = false;
		_format_errors.remove("Address.Tc");
	}


	protected String _node_name_ = $ADDRESS;

	/**
	 * Get the XML tag name for this instance.
	 */
	public String getXmlTagName () {
		return (_node_name_);
	}


	/**
	 * Set the XML tag name for this instance.
	 */
	public void setXmlTagName (String node_name) {
		_node_name_ = node_name;
	}


	/**
	 * Gets the XML tag name for this class.
	 */
	public static String getClassXmlTagName () {
		return ($ADDRESS);
	}


	/**
	 * Keeps track of format errors that are
	 * thrown in the numeric setXXX() methods().
	 */
	protected java.util.Hashtable _format_errors =
		new java.util.Hashtable();


	/**
	 * This flag is used to used to check whether
	 * the validators have been created.
	 */
	transient protected static boolean _validators_created = false;

	/*
	 * XML Validators
	 */
	transient protected static XmlStringValidator 
		_StreetAddress_validator_ = null;
	transient protected static XmlStringValidator 
		_City_validator_ = null;
	transient protected static XmlStringValidator 
		_State_validator_ = null;
	transient protected static XmlStringValidator 
		_Zip_validator_ = null;
	transient protected static XmlIntegerValidator
		_Tc_validator_ = null;

	/**
	 * Create the validators for this class.
	 */
	protected static synchronized void createValidators () {

		if (_validators_created) {
			return;
		}

		_StreetAddress_validator_ = new XmlStringValidator(
			"Address.StreetAddress", "Element", 
			"Address/StreetAddress", -1, -1, 1, 1);

		_City_validator_ = new XmlStringValidator(
			"Address.City", "Element", 
			"Address/City", -1, -1, 1, 1);

		_State_validator_ = new XmlStringValidator(
			"Address.State", "Element", 
			"Address/State", -1, -1, 1, 1);

		_Zip_validator_ = new XmlStringValidator(
			"Address.Zip", "Element", 
			"Address/Zip", -1, -1, 1, 1);

		_Tc_validator_ = new XmlIntegerValidator(
			"Address.Tc", "Attribute",
			"Address/tc",
			0, XmlValidator.NOT_USED,
			0, XmlValidator.NOT_USED, 0, 1);

		_validators_created = true;
	}


	/**
	 * Checks this object to see if it will produce valid XML.
	 */
	public boolean isValid () {

		if (!(this instanceof Validateable)) {
			return (true);
		}

		java.util.Vector errors = getValidationErrors(true);
		if (errors == null || errors.size() < 1) {
			return (true);
		}

		return (false);
	}


	/**
	 * Checks each field on the object for validity and
	 * returns a Vector holding the validation errors.
	 */
	public java.util.Vector getValidationErrors () {
		return (getValidationErrors(false));
	}


	/**
	 * Checks each field on the object for validity and
	 * returns a java.util.Vector holding the validation errors.
	 *
	 * @return  a Vector containing the validation errors
	 */
	public java.util.Vector getValidationErrors (boolean return_on_error) {
		return (getValidationErrors(return_on_error, true));
	}


	/**
	 * Checks each field on the object for validity and
	 * returns a Vector holding the validation errors.
	 *
	 * @return  a Vector containing the validation errors
	 */
	public java.util.Vector getValidationErrors (
		boolean return_on_error, boolean traverse) {

		createValidators();

		java.util.Vector errors;
		if (_unexpected_xml_errors_ != null &&
				_unexpected_xml_errors_.size() > 0) {
			errors = (java.util.Vector)_unexpected_xml_errors_.clone();
			if (return_on_error) {
				return (errors);
			}
		} else {
			errors = new java.util.Vector(4, 4);
		}

		XmlValidationError e;
		e = _StreetAddress_validator_.validate(
			_StreetAddress);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}

		e = _City_validator_.validate(
			_City);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}

		e = _State_validator_.validate(
			_State);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}

		e = _Zip_validator_.validate(
			_Zip);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}

		e = _Tc_validator_.validate(
			_Tc,
			_has_Tc_, _format_errors);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}


		if (errors.size() < 1) {
			return (null);
		}

		return (errors);
	}


	/**
	 * Checks the XML to see whether it matches the
	 * XML contents of this class.
	 */
	public static boolean matches (XmlElement xml, XmlObject parent) {

		if (xml == null) {
			return (false);
		}

		return (xml.matches($ADDRESS, nsm, parent));
	}


	/**
	 * This method unmarshals an XML document instance
	 * into an instance of this class.
	 */
	public static Address unmarshal (
			InputStream in) throws Exception {

		Address obj = new Address();
		ObjectFactory.unmarshal(obj, in);
		return (obj);
	}


	/**
	 * Populates this object with the values from the 
	 * parsed XML.
	 * @deprecated  will be removed in a future release.
	 * Use {@link #unmarshal(XmlElement)}.
	 */
	public void fromXml (XmlElement xml) {
		unmarshal(xml);
	}


	/**
	 * Populates this object with the values from the 
	 * parsed XML.
	 *
	 * @since 2.5
	 */
	public void unmarshal (XmlElement xml) {

		if (xml == null) {
			return;
		}

		if (!xml.matches($ADDRESS, this)) {
			return;
		}

		java.util.Vector doc_namespaces = xml.getDeclaredNamespaces();
		if (doc_namespaces != null) {
			_doc_declared_namespaces_ = 
				(java.util.Vector)doc_namespaces.clone();
		}

		unmarshalAttributes(xml);

		/*
		 * Get the contained XmlElement, this is what we process
		 */
		xml = xml.getChildAt(0);
		if (xml == null) {
			return;
		}

		if (xml.matches($STREET_ADDRESS, this)) {
			setStreetAddress(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}

		if (xml.matches($CITY, this)) {
			setCity(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}

		if (xml.matches($STATE, this)) {
			setState(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}

		if (xml.matches($ZIP, this)) {
			setZip(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}


		if (xml != null) {

			_unexpected_xml_errors_ =
				XmlValidationError.addUnexpectedXmlError(
					this, _unexpected_xml_errors_, xml);
		}
	}


	/**
	 * Unmarshal any attributes.
	 *
	 * @param xml the XmlElement holding the parsed XML
	 * @since 2.5
	 */
	protected void unmarshalAttributes (XmlElement xml) {

		/*
		 * Set the attribute based field(s)
		 */
		setTc(xml.getAttribute($TC, this));
	}


	/**
	 * Writes this instance to a stream. 
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @deprecated  This method will be removed in a future release.
	 * Use {@link #marshal(XmlOutputStream)} or {@link #marshal(OutputStream)}.
	 */
	public void toXml (OutputStream stream) {
		marshal(stream);
	}


	/**
	 * Writes this instance to a stream. 
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @param  embed_files  set to true to embed files in the XML
	 * @deprecated  This method will be removed in a future release.
	 * Use {@link #marshal(XmlOutputStream)} or {@link #marshal(OutputStream)}.
	 */
	public void toXml (OutputStream stream, boolean embed_files) {

		XmlOutputStream out = new FormattedOutputStream(stream);
		out.setEmbedFiles(embed_files);
		marshal(out);
	}


	/**
	 * Writes this instance to a stream. 
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @param  embed_files  set to true to embed files in the XML
	 * @deprecated  This method will be removed in a future release.
	 * Use {@link #marshal(XmlOutputStream)} or {@link #marshal(OutputStream)}.
	 */
	public void toXml (
			OutputStream stream, String indent, boolean embed_files)	{

		FormattedOutputStream out = new FormattedOutputStream(stream);
		out.setIndentString(indent);
		out.setEmbedFiles(embed_files);
		marshal(out);
	}


	/**
	 * Writes this instance to a stream. If the OutputStream is not an
	 * instance of XmlOutputStream then a FormattedOutputStream
	 * will be created which wraps the OutputStream.
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @see #marshal(XmlOutputStream)
	 * @since 2.5
	 */
	public void marshal (OutputStream stream) {

		XmlOutputStream out = new FormattedOutputStream(stream);
		marshal(out);
	}


	/**
	 * Writes this instance to an XmlOutputStream.
	 *
	 * @param  out  the XmlOutputStream to write the XML object to
	 * @see #marshal(OutputStream)
	 * @since 2.5
	 */
	public void marshal (XmlOutputStream out) {

		XmlAttributeList attrs = new XmlAttributeList(nsm);
		attrs = marshalAttributes(attrs);
		out.pushScope();
		out.writeStartTag(getXmlTagName(), attrs, false);
		out.incrementIndent();

		out.write($STREET_ADDRESS,
			_StreetAddress);
		out.write($CITY,
			_City);
		out.write($STATE,
			_State);
		out.write($ZIP,
			_Zip);

		out.decrementIndent();
		out.writeEndTag(getXmlTagName());
		out.popScope();
	}


	/**
	 * Get the XmlAttributeList for marshalling.
	 *
	 * @param attrs  the currently populated XmlAttributeList.
	 * @return  a populated XmlAttributeList
	 * @since 2.5
	 */
	protected XmlAttributeList marshalAttributes (XmlAttributeList attrs) {

		if (attrs == null) {
			attrs = new XmlAttributeList();
		}

		attrs.add($TC, _Tc, _has_Tc_);

		return (attrs);
	}


	/**
	 * Get this object's parent object.
	 */
	public XmlObject get$Parent () {
		return (_parent_);
	}


	/**
	 * Set this object's parent object.
	 */
	public void set$Parent (XmlObject parent) {
		_parent_ = parent;
	}


	/**
	 * The default <code>XmlNamespaceManager</code> for this class.
	 * @since 2.5
	 */
	public static XmlNamespaceManager nsm = null;


	/**
	 * Get the <code>XmlNamespaceManager</code> for this class.
	 * This will be null if no namespaces on this class or if
	 * namespace support is disabled during code generation.
	 *
	 * @since 2.5
	 */
	public XmlNamespaceManager get$NamespaceManager () {
		return (nsm);
	}


	/**
	 * Storage for namespaces declared in the input document.
	 * @since 2.5
	 */
	protected java.util.Vector _doc_declared_namespaces_ = null;


	/**
	 * Get the Vector holding the namespaces declared in the element
	 * that this instance was unmarshalled from.
	 *
	 * @since 2.5
	 */
	public java.util.Vector get$DocumentNamespaces () {
		return (_doc_declared_namespaces_);
	}
}
