/*
 * DO NOT EDIT!
 *
 * This file was generated by the Breeze XML Studio code generator.
 *
 *        Project: file:/C:/nbA/Requirement/EMSIAPS.xsd Binding
 *     Class Name: Policy
 *           Date: Mon Nov 11 14:43:37 CST 2002
 * Breeze Version: 3.0.0 build 382
 *
 * IMPORTANT: Please see your Breeze license for more information on
 *            where and how this generated code may be used.
 *
 */

package com.csc.fsg.nba.provideradapter.emsischema;


import java.io.InputStream;
import java.io.OutputStream;

import com.tbf.xml.FormattedOutputStream;
import com.tbf.xml.Validateable;
import com.tbf.xml.XmlAttributeList;
import com.tbf.xml.XmlElement;
import com.tbf.xml.XmlFloatValidator;
import com.tbf.xml.XmlIntegerValidator;
import com.tbf.xml.XmlNamespaceManager;
import com.tbf.xml.XmlObject;
import com.tbf.xml.XmlOutputStream;
import com.tbf.xml.XmlStringValidator;
import com.tbf.xml.XmlValidationError;
import com.tbf.xml.XmlValidator;

/**
 * Policy class.
 *
 */
public class Policy
	implements com.tbf.xml.XmlObject,
	com.tbf.xml.Validateable,
	java.io.Serializable {

	/**
	 * Constant for "Amount" node name.
	 */
	public static final String $AMOUNT = "Amount";

	/**
	 * Constant for "Type" node name.
	 */
	public static final String $TYPE = "Type";

	/**
	 * Constant for "Number" node name.
	 */
	public static final String $NUMBER = "Number";

	/**
	 * Constant for "Policy" node name.
	 */
	public static final String $POLICY = "Policy";


	/**
	 * Declarations for the XML related fields.
	 */
	protected String _Number = null;
	protected double _Amount = Double.NaN;
	protected boolean _has_Amount_ = false;
	protected int _Type = -1;
	protected boolean _has_Type_ = false;


	/**
	 * Holds the parent object of this object.
	 */
	protected transient XmlObject _parent_ = null;


	/**
	 * Storage for UNEXPECTED_XML errors.
	 */
	protected transient java.util.Vector _unexpected_xml_errors_ = null;


	/**
	 * Default no args constructor.
	 */
	public Policy () {
	}


	/**
	 * Creates and populates an instance from the provided parse tree.
	 *
	 * @param  xml  the parse tree
	 */
	public Policy (XmlElement xml) {
		unmarshal(xml);
	}


	/**
	 * Creates and populates an instance from the provided parse tree.
	 *
	 * @param  xml  the parse tree
	 * @param  parent  the containibg XmlObject
	 */
	public Policy (XmlElement xml, XmlObject parent) {
		_parent_ = parent;
		unmarshal(xml);
	}


	/**
	 * Get the Number property.
	 */
	public String getNumber () {
		return (_Number);
	}


	/**
	 * Set the Number property.
	 */
	public void setNumber (String newValue) {
		_Number = newValue;
	}


	/**
	 * Checks for whether Number is set or not.
	 *
	 * @return true if Number is set, false if not
	 */
	 public boolean hasNumber () {
		return (_Number != null);
	}


	/**
	 * Discards Number's value.
	 */
	 public void deleteNumber () {
		_Number = null;
	}


	/**
	 * Get the Amount property.
	 */
	public double getAmount () {
		if (_has_Amount_) {
			return (_Amount);
		}

		return (Double.NaN);
	}


	/**
	 * Set the Amount property.
	 */
	public void setAmount (double new_value) {
		_Amount = new_value;
		_has_Amount_ = true;
		_format_errors.remove("Policy.Amount");
	}


	public void setAmount (String new_value) {

		if (new_value == null) {
			_Amount = Double.NaN;
			_has_Amount_ = false;
			return;
		}

		try {
			_Amount = Double.valueOf(new_value).doubleValue();
			_has_Amount_ = true;
			_format_errors.remove("Policy.Amount");
		} catch (NumberFormatException nfe) {
			_has_Amount_ = false;
			XmlValidationError.addValidityFormatError(
				_format_errors, "Policy.Amount", "Element",
				"Policy/Amount", new_value);
		}
	}


	/**
	 * Checks for whether Amount is set or not.
	 *
	 * @return true if Amount is set, false if not
	 */
	public boolean hasAmount () {
		return (_has_Amount_);
	}


	/**
	 * Discards Amount's value.
	 */
	public void deleteAmount () {
		_has_Amount_ = false;
		_format_errors.remove("Policy.Amount");
	}


	/**
	 * Get the Type property.
	 */
	public int getType () {
		if (_has_Type_) {
			return (_Type);
		}

		return (-1);
	}


	/**
	 * Set the Type property.
	 */
	public void setType (int new_value) {
		_Type = new_value;
		_has_Type_ = true;
		_format_errors.remove("Policy.Type");
	}


	public void setType (String new_value) {

		if (new_value == null) {
			_Type = -1;
			_has_Type_ = false;
			return;
		}

		try {
			_Type = Integer.parseInt(new_value);
			_has_Type_ = true;
			_format_errors.remove("Policy.Type");
		} catch (NumberFormatException nfe) {
			_has_Type_ = false;
			XmlValidationError.addValidityFormatError(
				_format_errors, "Policy.Type", "Element",
				"Policy/Type", new_value);
		}
	}


	/**
	 * Checks for whether Type is set or not.
	 *
	 * @return true if Type is set, false if not
	 */
	public boolean hasType () {
		return (_has_Type_);
	}


	/**
	 * Discards Type's value.
	 */
	public void deleteType () {
		_has_Type_ = false;
		_format_errors.remove("Policy.Type");
	}


	protected String _node_name_ = $POLICY;

	/**
	 * Get the XML tag name for this instance.
	 */
	public String getXmlTagName () {
		return (_node_name_);
	}


	/**
	 * Set the XML tag name for this instance.
	 */
	public void setXmlTagName (String node_name) {
		_node_name_ = node_name;
	}


	/**
	 * Gets the XML tag name for this class.
	 */
	public static String getClassXmlTagName () {
		return ($POLICY);
	}


	/**
	 * Keeps track of format errors that are
	 * thrown in the numeric setXXX() methods().
	 */
	protected java.util.Hashtable _format_errors =
		new java.util.Hashtable();


	/**
	 * This flag is used to used to check whether
	 * the validators have been created.
	 */
	transient protected static boolean _validators_created = false;

	/*
	 * XML Validators
	 */
	transient protected static XmlStringValidator 
		_Number_validator_ = null;
	transient protected static XmlFloatValidator
		_Amount_validator_ = null;
	transient protected static XmlIntegerValidator
		_Type_validator_ = null;

	/**
	 * Create the validators for this class.
	 */
	protected static synchronized void createValidators () {

		if (_validators_created) {
			return;
		}

		_Number_validator_ = new XmlStringValidator(
			"Policy.Number", "Element", 
			"Policy/Number", -1, -1, 1, 1);

		_Amount_validator_ = new XmlFloatValidator(
			"Policy.Amount", "Element",
			"Policy/Amount",
			0.0, XmlValidator.NOT_USED,
			0.0, XmlValidator.NOT_USED, 1, 1);

		_Type_validator_ = new XmlIntegerValidator(
			"Policy.Type", "Element",
			"Policy/Type",
			0, XmlValidator.NOT_USED,
			0, XmlValidator.NOT_USED, 1, 1);

		_validators_created = true;
	}


	/**
	 * Checks this object to see if it will produce valid XML.
	 */
	public boolean isValid () {

		if (!(this instanceof Validateable)) {
			return (true);
		}

		java.util.Vector errors = getValidationErrors(true);
		if (errors == null || errors.size() < 1) {
			return (true);
		}

		return (false);
	}


	/**
	 * Checks each field on the object for validity and
	 * returns a Vector holding the validation errors.
	 */
	public java.util.Vector getValidationErrors () {
		return (getValidationErrors(false));
	}


	/**
	 * Checks each field on the object for validity and
	 * returns a java.util.Vector holding the validation errors.
	 *
	 * @return  a Vector containing the validation errors
	 */
	public java.util.Vector getValidationErrors (boolean return_on_error) {
		return (getValidationErrors(return_on_error, true));
	}


	/**
	 * Checks each field on the object for validity and
	 * returns a Vector holding the validation errors.
	 *
	 * @return  a Vector containing the validation errors
	 */
	public java.util.Vector getValidationErrors (
		boolean return_on_error, boolean traverse) {

		createValidators();

		java.util.Vector errors;
		if (_unexpected_xml_errors_ != null &&
				_unexpected_xml_errors_.size() > 0) {
			errors = (java.util.Vector)_unexpected_xml_errors_.clone();
			if (return_on_error) {
				return (errors);
			}
		} else {
			errors = new java.util.Vector(4, 4);
		}

		XmlValidationError e;
		e = _Number_validator_.validate(
			_Number);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}

		e = _Amount_validator_.validate(
			_Amount,
			_has_Amount_, _format_errors);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}

		e = _Type_validator_.validate(
			_Type,
			_has_Type_, _format_errors);
		if (e != null) {
			errors.addElement(e);
			if (return_on_error) {
				return (errors);
			}
		}


		if (errors.size() < 1) {
			return (null);
		}

		return (errors);
	}


	/**
	 * Checks the XML to see whether it matches the
	 * XML contents of this class.
	 */
	public static boolean matches (XmlElement xml, XmlObject parent) {

		if (xml == null) {
			return (false);
		}

		return (xml.matches($POLICY, nsm, parent));
	}


	/**
	 * This method unmarshals an XML document instance
	 * into an instance of this class.
	 */
	public static Policy unmarshal (
			InputStream in) throws Exception {

		Policy obj = new Policy();
		ObjectFactory.unmarshal(obj, in);
		return (obj);
	}


	/**
	 * Populates this object with the values from the 
	 * parsed XML.
	 * @deprecated  will be removed in a future release.
	 * Use {@link #unmarshal(XmlElement)}.
	 */
	public void fromXml (XmlElement xml) {
		unmarshal(xml);
	}


	/**
	 * Populates this object with the values from the 
	 * parsed XML.
	 *
	 * @since 2.5
	 */
	public void unmarshal (XmlElement xml) {

		if (xml == null) {
			return;
		}

		if (!xml.matches($POLICY, this)) {
			return;
		}

		java.util.Vector doc_namespaces = xml.getDeclaredNamespaces();
		if (doc_namespaces != null) {
			_doc_declared_namespaces_ = 
				(java.util.Vector)doc_namespaces.clone();
		}

		unmarshalAttributes(xml);

		/*
		 * Get the contained XmlElement, this is what we process
		 */
		xml = xml.getChildAt(0);
		if (xml == null) {
			return;
		}

		if (xml.matches($NUMBER, this)) {
			setNumber(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}

		if (xml.matches($AMOUNT, this)) {
			setAmount(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}

		if (xml.matches($TYPE, this)) {
			setType(xml.getData());
			xml = xml.next();
			if (xml == null) {
				return;
			}
		}

		if (xml != null) {

			_unexpected_xml_errors_ =
				XmlValidationError.addUnexpectedXmlError(
					this, _unexpected_xml_errors_, xml);
		}
	}


	/**
	 * Unmarshal any attributes.
	 *
	 * @param xml the XmlElement holding the parsed XML
	 * @since 2.5
	 */
	protected void unmarshalAttributes (XmlElement xml) {
	}


	/**
	 * Writes this instance to a stream. 
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @deprecated  This method will be removed in a future release.
	 * Use {@link #marshal(XmlOutputStream)} or {@link #marshal(OutputStream)}.
	 */
	public void toXml (OutputStream stream) {
		marshal(stream);
	}


	/**
	 * Writes this instance to a stream. 
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @param  embed_files  set to true to embed files in the XML
	 * @deprecated  This method will be removed in a future release.
	 * Use {@link #marshal(XmlOutputStream)} or {@link #marshal(OutputStream)}.
	 */
	public void toXml (OutputStream stream, boolean embed_files) {

		XmlOutputStream out = new FormattedOutputStream(stream);
		out.setEmbedFiles(embed_files);
		marshal(out);
	}


	/**
	 * Writes this instance to a stream. 
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @param  embed_files  set to true to embed files in the XML
	 * @deprecated  This method will be removed in a future release.
	 * Use {@link #marshal(XmlOutputStream)} or {@link #marshal(OutputStream)}.
	 */
	public void toXml (
			OutputStream stream, String indent, boolean embed_files)	{

		FormattedOutputStream out = new FormattedOutputStream(stream);
		out.setIndentString(indent);
		out.setEmbedFiles(embed_files);
		marshal(out);
	}


	/**
	 * Writes this instance to a stream. If the OutputStream is not an
	 * instance of XmlOutputStream then a FormattedOutputStream
	 * will be created which wraps the OutputStream.
	 *
	 * @param  stream  the OutputStream to write the XML object to
	 * @see #marshal(XmlOutputStream)
	 * @since 2.5
	 */
	public void marshal (OutputStream stream) {

		XmlOutputStream out = new FormattedOutputStream(stream);
		marshal(out);
	}


	/**
	 * Writes this instance to an XmlOutputStream.
	 *
	 * @param  out  the XmlOutputStream to write the XML object to
	 * @see #marshal(OutputStream)
	 * @since 2.5
	 */
	public void marshal (XmlOutputStream out) {

		XmlAttributeList attrs = new XmlAttributeList(nsm);
		attrs = marshalAttributes(attrs);
		out.pushScope();
		out.writeStartTag(getXmlTagName(), attrs, false);
		out.incrementIndent();

		out.write($NUMBER,
			_Number);
		out.write($AMOUNT,
			_Amount, _has_Amount_);
		out.write($TYPE,
			_Type, _has_Type_);

		out.decrementIndent();
		out.writeEndTag(getXmlTagName());
		out.popScope();
	}


	/**
	 * Get the XmlAttributeList for marshalling.
	 *
	 * @param attrs  the currently populated XmlAttributeList.
	 * @return  a populated XmlAttributeList
	 * @since 2.5
	 */
	protected XmlAttributeList marshalAttributes (XmlAttributeList attrs) {

		return (attrs);
	}


	/**
	 * Get this object's parent object.
	 */
	public XmlObject get$Parent () {
		return (_parent_);
	}


	/**
	 * Set this object's parent object.
	 */
	public void set$Parent (XmlObject parent) {
		_parent_ = parent;
	}


	/**
	 * The default <code>XmlNamespaceManager</code> for this class.
	 * @since 2.5
	 */
	public static XmlNamespaceManager nsm = null;


	/**
	 * Get the <code>XmlNamespaceManager</code> for this class.
	 * This will be null if no namespaces on this class or if
	 * namespace support is disabled during code generation.
	 *
	 * @since 2.5
	 */
	public XmlNamespaceManager get$NamespaceManager () {
		return (nsm);
	}


	/**
	 * Storage for namespaces declared in the input document.
	 * @since 2.5
	 */
	protected java.util.Vector _doc_declared_namespaces_ = null;


	/**
	 * Get the Vector holding the namespaces declared in the element
	 * that this instance was unmarshalled from.
	 *
	 * @since 2.5
	 */
	public java.util.Vector get$DocumentNamespaces () {
		return (_doc_declared_namespaces_);
	}
}
