package com.csc.fsg.nba.webservice.client;
/* 
 * *******************************************************************************<BR>
 * This program contains trade secrets and confidential information which<BR>
 * are proprietary to CSC Financial Services Group®.  The use,<BR>
 * reproduction, distribution or disclosure of this program, in whole or in<BR>
 * part, without the express written permission of CSC Financial Services<BR>
 * Group is prohibited.  This program is also an unpublished work protected<BR>
 * under the copyright laws of the United States of America and other<BR>
 * countries.  If this program becomes published, the following notice shall<BR>
 * apply:
 *     Property of Computer Sciences Corporation.<BR>
 *     Confidential. Not for publication.<BR>
 *     Copyright (c) 2002-2008 Computer Sciences Corporation. All Rights Reserved.<BR>
 * 
 * *******************************************************************************<BR>
 */
import com.csc.fsg.nba.foundation.NbaLogFactory;
import com.csc.fsg.nba.vo.NbaTXLife;
/**
 * NbaAgentValidationClient is the warpper class on actual client class for AgentValidation WebService.
 * <p>
 * <b>Modifications:</b><br>
 * <table border=0 cellspacing=5 cellpadding=5>
 * <thead>
 * <th align=left>Project</th><th align=left>Release</th><th align=left>Description</th>
 * </thead>
 * <tr><td>NBA073</td><td>Version 3</td><td>Agent Validation</td></tr>
 * <tr><td>ACN012</td><td>Version 4</td><td>Architecture Changes</td></tr>
 * <tr><td>NBA103</td><td>Version 4</td><td>Logging</td></tr>
 * <tr><td>SPR2968</td><td>Version 6</td><td>Test web service should determine XML file name dynamically</td></tr>
 * </table>
 * <p>
 * @author CSC FSG Developer
 * @version 7.0.0
 * @since New Business Accelerator - Version 3
 */
public class NbaAgentValidationClient extends NbaWebServiceAdapterBase {
	protected AgentValidationProxy proxyClient = null;
	/**
	 * Constructor for NbaAgentValidationClient.
	 */
	public NbaAgentValidationClient() {
		super();
	}
	/**
	 * Takes two parameters and calls the AgentValidation proxy Client class. After instantiating the proxy client 
	 * this method passes agent validation transaction(514) and one more object in client and gets the response xml back 
	 * from WebService.
	 * @param nbATxLife An instance of <code>NbaTXLife</code>
	 * @param obj An instance of <code>Object</code>
	 * @return NbaTXLife response returned from WebService
	 */
	public NbaTXLife invokeWebService(NbaTXLife nbATxLife) { // SPR2968
		NbaTXLife response = null;
		try {
			proxyClient = new AgentValidationProxy(); //object of proxy client generated by WSAD
			proxyClient.setAccess(getAccess()); //set Access
			proxyClient.setTargetUri(getTargetUri()); //set targetUri
			proxyClient.setWsdlUrl(getWsdlUrl()); //set WsdlUrl
			response = proxyClient.invokeWebService(nbATxLife); // SPR2968
			//pass NbaTXLife and fineName
		} catch (Exception e) {
			NbaLogFactory.getLogger(this.getClass()).logException(e); //NBA103
		}
		return response;
	}
}
